#服务器端口
server:
  port: 80

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://rdsn9nu3529brazvsickj.mysql.rds.aliyuncs.com:3306/rdsn9nu3529brazvsickj?useUnicode=true&amp;characterEncoding=UTF-8
    username: chris1943
    password: chris1943
